### ISSUE TITLE
Boss AI changes

### ISSUE THREAD

**Issue by MouaYing** [MouaYing/ScrollThief#70]
Desired: Boss has 3 phases: Pouncing, small shot volley, and big shot volley. There is never a point when it is just standing there. Boss's body only rotates while it is winding up to pounce, or winding up to shoot. Boss winds up before charging up a big shot, and also before a volley of smalls. Once a volley begins, boss does not rotate, but spews out small fireballs at a rate of about 2 per second (pretty much the animation loops) for around 4-6 seconds. These shots chase the ninja, but have a limited turning rate so it is possible to out-maneuver them. Big shots start with the windup, then charge for 2-2.5 seconds or so, then fire in a straight line. Boss's hitbox matches its own dimensions.

Current: Small shots have no wind up, volley is slow and only shoots about 2 times. All shots go straight. Big shots wind up, but don't charge. Boss's hitbox does not mach its dimensions.

**Comment by Besendorfer** [comment]
I agree with these. One thing that is very frustrating currently is that
the boss follow the ninja perfectly, thus the ninja only has a chance to
hit the boss's head. Because there is no charge up, it is essentially
impossible to dodge the boss's little fireballs. :(

**Comment by MouaYing** [comment]
Yeah, the boss was not supposed to rotate to stay facing the ninja while shooting a volley. There is no animation for rotating, so I wanted to minimize the boss's rotations as much as possible. That's the entire reason the small shots were supposed to seek the ninja: because it would look bad to have the boss rotate during a volley.

**Comment by taftsandbakken** [comment]
I like how clearly you define how the boss should function, however I don't think I knew too much of that before now and so we're almost out of time. It was my mistake to not fast prototype so you all could test and give input, and for that I apologize.

Things that are done and in master now:
-Pause Menu has the scroll image. The button images aren't showing for some reason, but I kinda like it that way. What do you all think?
-The boss now gets hurt when hit (the health bar always worked).
-The boss now only spins right before shooting, so you can go around him and hit his flank a few times
-The boss shoots out several shots in a fan burst (instead of a volley). This is from before I knew you wanted a volley. I had it set to only happen when the boss has low health but I turned that off so you can see it from the beginning.

Things not done:
-The level loading bar doesn't update and I don't know why :(
-The hitbox for the attacking collision is still off, but I was waiting for Kevin to merge his changes before I fixed that.
-The boss does not yet shoot in a volley.
-The boss does the charge animation before the big shot and frenzy attack, but I don't have any added delay on top of that.
-I was never able to get the small shots to heat seek properly.

So... I only have a little bit of time left. Unfortunately I won't be able to get to all of the things in the list. At the very least I will fix the strike collision but I can't promise much more than that.
